#!/usr/bin/env sh

set -e

function usage() {
	>&2 echo "kubectl renew pod|deployment NAME"
	exit 1
}

if [[ "$#" != "2" ]]; then
	>&2 echo "Invalid number of arguments."
	usage
	exit 1
fi

KIND="$1"
NAME="$2"
NS="$KUBECTL_PLUGINS_CURRENT_NAMESPACE"

function renew_pod() {
	kubectl get po "$1" -n "$NS" -o yaml | kubectl replace --force -f -
}


case $KIND in
	pod)
		renew_pod "$NAME" ;;
	deployment)
		selfLink=$(kubectl get deployment.apps "$NAME" -n "$NS" -o jsonpath={.metadata.selfLink})
		selector=$(kubectl get --raw "${selfLink}/scale" | jq -r .status.selector)
		PODS=$(kubectl get pods --no-headers -n "$NS" -l "$selector" | cut -d' ' -f1)
		for pod in $PODS; do
			renew_pod "$pod"
		done ;;
	*)
		>&2 echo "Invalid argument."
		usage ;;
esac
