#!/usr/bin/env sh

set -e

function usage() {
	>&2 echo "kubectl renew pod|deployment|daemonset|rc NAME"
	exit 1
}

if [[ "$#" != "2" ]]; then
	>&2 echo "Invalid number of arguments."
	usage
	exit 1
fi

KIND="$1"
NAME="$2"
NS="$KUBECTL_PLUGINS_CURRENT_NAMESPACE"

function renew_pod() {
	kubectl get po "$1" -n "$NS" -o yaml | kubectl replace --force -f -
}


case $KIND in
	pod)
		renew_pod "$NAME" ;;
	deployment|daemonset|rc)
		selector=$(kubectl get $KIND $NAME --output=json | jq -j '.spec.selector.matchLabels | to_entries | .[] | "\(.key)=\(.value),"')
		pods=$(kubectl get pods --selector="${selector%?}" --output=jsonpath={.items..metadata.name})
		for pod in $pods; do
			renew_pod "$pod"
		done ;;
	*)
		>&2 echo "Invalid argument."
		usage ;;
esac
